config:
  target: 'http://localhost:3000'
  phases:
    - duration: 60
      arrivalRate: 10
      name: 'Warm up'
    - duration: 120
      arrivalRate: 50
      name: 'Load test'
    - duration: 60
      arrivalRate: 100
      name: 'Peak load'
    - duration: 60
      arrivalRate: 10
      name: 'Cool down'

scenarios:
  - name: 'API Load Test'
    weight: 70
    flow:
      - get:
          url: '/health'
      - think: 1
      - post:
          url: '/auth/login'
          json:
            email: 'test@example.com'
            password: 'password123'
      - think: 2
      - get:
          url: '/users/profile'
          headers:
            Authorization: 'Bearer {{ token }}'
      - think: 1

  - name: 'Database Operations'
    weight: 30
    flow:
      - get:
          url: '/users'
          headers:
            Authorization: 'Bearer {{ token }}'
      - think: 2
      - post:
          url: '/users'
          headers:
            Authorization: 'Bearer {{ token }}'
          json:
            email: 'test-{{ $randomString() }}@example.com'
            name: 'Test User'
      - think: 1
